#!/bin/sh

set -e

soversion=$(sh ./get-soversion.sh)

infile=./debian/control.in
outfile=./debian/control

cat > $outfile <<EOF
# This file is autogenerated. DO NOT EDIT!
#
# Modifications should be made to debian/control.in instead.
# This file is regenerated automatically in the clean target.
#
EOF

sed -e "s/@MS_SOVERSION@/${soversion}/" < $infile >> $outfile

exit 0
